baseURL = "https://zarldev.github.io/tsk/"
title = "tsk"
theme = "hugo-book"

enableGitInfo = false

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "docs"
  BookRepo = "https://github.com/zarldev/tsk"
